### ISSUE TITLE
Error message when trying to run command_parser with v2.7.1

### ISSUE THREAD

**Issue by smitsialis** [ansible-network/cisco_ios#105]
v2.7.1 gives an error message when trying to run the command_parser.  It does work with v2.7.0. 
 It's reporting that network-engine is running the wrong version when it is not.<br>
```
TASK [ansible-network.cisco_ios : Validate we have required installed version of dependent roles from meta] ****************************************************
fatal: [cisco_switch]: FAILED! => {"changed": false, "msg": "Error! : role: ansible-network.network-engine installed version :v2.7.2 is less than required version: v2.7.3"}
```
The installed version of network-engine is v2.7.3.  Have also tried v2.7.5 with same exact error message.<br>cisco_ios v2.7.0 works with both network-engine v2.7.3 and v2.75.
```
Role: ansible-network.network-engine
        description: This role provides the foundation for building network roles by providing modules and plugins that are common to all Ansible Network roles.
        active: True
        commit: d9106df0c2a8531b90974a737d3a0ee67ef3e8e2
        commit_message: Merge pull request #231 from trishnaguha/v275changelog

v275 changelog

Reviewed-by: https://github.com/softwarefactory-project-zuul[bot]
        commit_url: https://api.github.com/repos/ansible-network/network-engine/git/commits/d9106df0c2a8531b90974a737d3a0ee67ef3e8e2
        company: Red Hat
        created: 2018-04-23T13:20:20.814748Z
        dependencies: []
        download_count: 8236
        forks_count: 43
        galaxy_info:
                author: ansible-network
                company: Red Hat
                galaxy_tags: ['ansible', 'network', 'networking', 'engine', 'core', 'cli']
                issue_tracker_url: https://github.com/ansible-network/network-engine/issues
                license: GPLv3
                min_ansible_version: 2.7
                platforms: [{'name': 'network', 'versions': ['all']}]
        github_branch: HEAD
        github_repo: network-engine
        github_user: ansible-network
        id: 25206
        imported: 2019-03-05T10:54:39.640009-05:00
        install_date: Sat Mar 30 13:15:24 2019
        installed_version: v2.7.3
        is_valid: True
        issue_tracker_url: https://github.com/ansible-network/network-engine/issues
        license: GPLv3
        min_ansible_version: 2.7
        modified: 2019-03-05T15:54:39.710708Z
        open_issues_count: 8
        path: [u'/home/smitsi1/.ansible/roles', u'/usr/share/ansible/roles', u'/etc/ansible/roles']
        role_type: ANS
        stargazers_count: 75
        travis_status_url:
```
failing playbook:
```
    - name: Get show power inline
      ios_command:
        commands: "show power inline"
      register: result

    - name: import the network-engine role
      import_role:
        name: ansible-network.cisco_ios

    - name: Parse the results
      command_parser:
        file: "parsers/show_power_inline.yaml"
        content: "{{ result.stdout.0 }}"
```
