### ISSUE TITLE
show ip bgp sum should always be a list

### ISSUE THREAD

**Issue by IPvSean** [ansible-network/cisco_ios#76]
with respect to: https://github.com/ansible-network/cisco_ios/blob/devel/parser_templates/cli/show_ip_bgp_summary.yaml

I feel like the output of show ip bgp summary should always be a list using the filter

here is my output
```
ok: [rtr2] => changed=false
  ansible_facts:
    cisco_ios:
      vrf:
        DEFAULT:
          protocols:
            bgp:
              neighbors:
                172.17.124.126:
                  asn: '65004'
                  ip_version: '4'
                  state_pfxrcd: '0'
                  timer: 04:31:33
              process_state: active
  included:
  - /home/student1/.ansible/roles/ansible-network.cisco_ios/parser_templates/cli/show_ip_bgp_summary.yaml
```

otherwise trying to print out the neighbor info for multiple vs one is different and you got to have logic in the playbook for that
